export const userTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  //sign in
  GOOGLE_SIGNIN_START: 'GOOGLE_SIGNIN_START',
  EMAIL_SIGNIN_START: 'EMAIL_SIGNIN_START',
  //sign in progress
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',
  //check sesion
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  //signout
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCCESS: 'SIGN_OUT_SUCCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',

  //SINGUP
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCCESS: 'SIGN_UP_SUCCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};
